from django.contrib import admin
from django.urls import path, include
from maison_app import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.accueil, name='accueil'),
    path('faq/', views.faq, name='faq'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('taches/', views.liste_taches, name='liste_taches'),
    path('foyers/', views.liste_foyers, name='liste_foyers'),
    path('utilisateurs/', views.liste_utilisateurs, name='liste_utilisateurs'),
    path('creer-foyer/', views.creer_foyer, name='creer_foyer'),
    path('foyer/<int:foyer_id>/modifier/', views.modifier_foyer, name='modifier_foyer'),
    path('ajouter-tache/', views.ajouter_tache, name='ajouter_tache'),
    path('foyer/<int:foyer_id>/inviter/', views.generer_invitation, name='generer_invitation'),  # ← AJOUTÉ
    path('rejoindre/', views.rejoindre_foyer, name='rejoindre_foyer'),
    path('rejoindre/<uuid:code>/', views.rejoindre_foyer, name='rejoindre'),
    path('accounts/login/', views.custom_login, name='login'),
    path('tache/<int:tache_id>/', views.detail_tache, name='detail_tache'),
    path('tache/<int:tache_id>/modifier/', views.modifier_tache, name='modifier_tache'),
    path('tache/<int:tache_id>/annuler/', views.annuler_tache_terminee, name='annuler_tache_terminee'),
    path('tache/<int:tache_id>/supprimer/', views.supprimer_tache, name='supprimer_tache'),
    path('ajouter-piece/', views.ajouter_piece, name='ajouter_piece'),
    path('foyer/<int:foyer_id>/supprimer/', views.supprimer_foyer, name='supprimer_foyer'),
    path('ajouter-animal/', views.ajouter_animal, name='ajouter_animal'),
    path('piece/<int:piece_id>/supprimer/', views.supprimer_piece, name='supprimer_piece'),
    path('animal/<int:animal_id>/supprimer/', views.supprimer_animal, name='supprimer_animal'),
    path('invitation/<int:foyer_id>/', views.generer_invitation, name='generer_invitation'),
    path('logout/', views.custom_logout, name='logout'),
    path('utilisateurs-par-foyer/', views.liste_utilisateurs_par_foyer, name='liste_utilisateurs_par_foyer'),
    path('foyer/<int:foyer_id>/', views.detail_foyer, name='detail_foyer'),
    path('foyer/<int:foyer_id>/statistiques/', views.statistiques_foyer, name='statistiques_foyer'),
    path('statistiques-membre/', views.statistiques_membre, name='statistiques_membre'),
    path('statistiques-membre/<int:user_id>/', views.statistiques_membre, name='statistiques_membre_detail'),
    path('supprimer-membre/<int:user_id>/', views.supprimer_membre, name='supprimer_membre'),
    path('terminer-tache/<int:tache_id>/', views.terminer_tache, name='terminer_tache'),
    path('inscription/', views.inscription, name='inscription'),
    path('foyer/<int:foyer_id>/chat/', views.chat_foyer, name='chat_foyer'),
    path('mes-notes/', views.mes_notes, name='mes_notes'),
    path('mon_profil/', views.mon_profil, name='mon_profil'),
    path('mon-profil/', views.mon_profil, name='mon_profil_alt'),  # URL alternative avec tiret pour compatibilité
    path('mes-notifications/', views.mes_notifications, name='mes_notifications'),
    path('notification/<int:id>/lue/', views.marquer_notification_lue, name='marquer_notification_lue'),
    path('notification/<int:id>/supprimer/', views.supprimer_notification, name='supprimer_notification'),
    path('budget/', views.budget_foyer, name='budget_foyer'),
    path('budget/historique/', views.historique_depenses, name='historique_depenses'),
    path('budget/export-pdf/', views.export_budget_pdf, name='export_budget_pdf'),
    path('budget/export-excel/', views.export_budget_excel, name='export_budget_excel'),
    path('ajouter-depense/', views.ajouter_depense, name='ajouter_depense'),
    path('depense/<int:id>/supprimer/', views.supprimer_depense, name='supprimer_depense'),
    path('ajouter-budget/', views.ajouter_budget, name='ajouter_budget'),
    path('mes-demandes/', views.mes_demandes, name='mes_demandes'),
    path('creer-demande/', views.creer_demande, name='creer_demande'),
    path('gerer-demandes/', views.gerer_demandes, name='gerer_demandes'),
    path('demandes/', views.liste_demandes_foyer, name='liste_demandes_foyer'),
    path('api/notifications-count/', views.api_notifications_count, name='api_notifications_count'),
    path('api/demandes-count/', views.api_demandes_count, name='api_demandes_count'),
    path('api/foyer/<int:foyer_id>/chat/send/', views.api_send_message, name='api_send_message'),
    path('api/foyer/<int:foyer_id>/chat/messages/', views.api_get_messages, name='api_get_messages'),
    path('api/foyer/<int:foyer_id>/chat/message/<int:message_id>/delete/', views.api_delete_message, name='api_delete_message'),
    path('api/foyer/<int:foyer_id>/chat/message/<int:message_id>/edit/', views.api_edit_message, name='api_edit_message'),
    # Routes temporairement commentées - à réactiver si les fonctions existent
    path('mes-recompenses/', views.mes_recompenses, name='mes_recompenses'),
    path('tache/<int:tache_id>/demander-modification/', views.demander_modification_date, name='demander_modification_date'),
    path('gerer-demandes-modification/', views.gerer_demandes_modification, name='gerer_demandes_modification'),
    path('demande-modification/<int:demande_id>/<str:action>/', views.traiter_demande_modification, name='traiter_demande_modification'),
    path('calendrier/', views.calendrier_taches, name='calendrier_taches'),
    path('piece/<int:piece_id>/', views.detail_piece, name='detail_piece'),
    path('piece/<int:piece_id>/snake/', views.liste_niveaux_snake, name='liste_niveaux_snake'),
    path('piece/<int:piece_id>/snake/niveau/<int:niveau_id>/', views.jouer_snake, name='jouer_snake'),
    path('piece/<int:piece_id>/snake/niveau/<int:niveau_id>/debloquer/', views.debloquer_niveau_snake, name='debloquer_niveau_snake'),
    path('piece/<int:piece_id>/snake/niveau/<int:niveau_id>/score/', views.sauvegarder_score_snake, name='sauvegarder_score_snake'),
    path('cuisine/<int:piece_id>/', views.cuisine_view, name='cuisine_view'),
    path('cuisine/<int:piece_id>/stock/', views.gerer_stock, name='gerer_stock'),
    path('api/get-weather/', views.api_get_weather, name='api_get_weather'),
    path('api/meteo/favorite/add/', views.api_add_favorite_city, name='api_add_favorite_city'),
    path('api/meteo/favorite/remove/', views.api_remove_favorite_city, name='api_remove_favorite_city'),
    path('cuisine/<int:piece_id>/liste-courses/', views.liste_courses_cuisine, name='liste_courses_cuisine'),
    path('cuisine/<int:piece_id>/liste-courses/<int:liste_id>/', views.detail_liste_courses, name='detail_liste_courses'),
    path('cuisine/<int:piece_id>/menus/', views.menus_semaine, name='menus_semaine'),
    path('cuisine/<int:piece_id>/menus/<int:menu_id>/', views.detail_menu_semaine, name='detail_menu_semaine'),
    path('cuisine/<int:piece_id>/recettes/', views.generer_recettes, name='generer_recettes'),
    path('cuisine/<int:piece_id>/recettes/historique/', views.historique_recettes, name='historique_recettes'),
    path('historique-taches/', views.historique_taches, name='historique_taches'),
    path('suggestions-taches/', views.suggestions_taches, name='suggestions_taches'),
    path('recherche/', views.recherche, name='recherche'),
    path('proposer-suggestion/', views.proposer_suggestion, name='proposer_suggestion'),
    path('gerer-suggestion/<int:suggestion_id>/', views.gerer_suggestion, name='gerer_suggestion'),
    path('mes-preferences/', views.mes_preferences, name='mes_preferences'),
    path('mes-statistiques/', views.mes_statistiques, name='mes_statistiques'),
    # ===== INTERACTIONS IA - COMMENTÉ =====
    # path('interaction-ia/', views.interaction_ia, name='interaction_ia'),
    path('dispositifs/', views.liste_dispositifs, name='liste_dispositifs'),
    path('ajouter-dispositif/', views.ajouter_dispositif, name='ajouter_dispositif'),
    path('modifier-dispositif/<int:dispositif_id>/', views.modifier_dispositif, name='modifier_dispositif'),
    path('supprimer-dispositif/<int:dispositif_id>/', views.supprimer_dispositif, name='supprimer_dispositif'),
    path('historique-actions-dispositifs/', views.historique_actions_dispositifs, name='historique_actions_dispositifs'),
    # ===== UTILISATION RESSOURCE - COMMENTÉ =====
    # path('utilisation-ressources/', views.utilisation_ressources, name='utilisation_ressources'),
    # ===== TUTO - COMMENTÉ =====
    # path('tutos/', views.liste_tutos, name='liste_tutos'),
    path('ajouter-evenement/', views.ajouter_evenement, name='ajouter_evenement'),
    path('modifier-evenement/<int:evenement_id>/', views.modifier_evenement, name='modifier_evenement'),
    path('supprimer-evenement/<int:evenement_id>/', views.supprimer_evenement, name='supprimer_evenement'),
]

# ← SERVIR LES FICHIERS MÉDIAS ET STATIQUES EN DÉVELOPPEMENT
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()