# Generated by Django 5.2.7 on 2025-11-03 08:33

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nb_pieces', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'foyer',
            },
        ),
        migrations.CreateModel(
            name='StatutTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(choices=[('À faire', 'À faire'), ('En cours', 'En cours'), ('Terminée', 'Terminée'), ('Annulée', 'Annulée')], max_length=50)),
            ],
            options={
                'db_table': 'statut_tache',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('tresorier', 'Trésorier'), ('membre', 'Membre'), ('junior', 'Junior'), ('invite', 'Invité'), ('superviseur', 'Superviseur'), ('observateur', 'Observateur')], default='membre', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('id_foyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maison_app.foyer')),
            ],
            options={
                'db_table': 'utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(null=True)),
                ('id_foyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maison_app.foyer')),
            ],
            options={
                'db_table': 'evenement',
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_depense', models.DateField()),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_foyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maison_app.foyer')),
            ],
            options={
                'db_table': 'depense',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_restant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periode', models.CharField(choices=[('mois', 'Mois'), ('annee', 'Année')], max_length=10)),
                ('id_foyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maison_app.foyer')),
            ],
            options={
                'db_table': 'budget',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('tresorier', 'Trésorier'), ('membre', 'Membre'), ('junior', 'Junior'), ('invite', 'Invité'), ('superviseur', 'Superviseur'), ('observateur', 'Observateur')], default='membre', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilise', models.BooleanField(default=False)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('foyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maison_app.foyer')),
            ],
        ),
        migrations.CreateModel(
            name='ListeCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('En cours', 'En cours'), ('Acheté', 'Acheté')], max_length=20)),
                ('id_foyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maison_app.foyer')),
            ],
            options={
                'db_table': 'liste_courses',
            },
        ),
        migrations.CreateModel(
            name='Aliment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('unite', models.CharField(max_length=20, null=True)),
                ('id_liste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maison_app.listecourses')),
            ],
            options={
                'db_table': 'aliment',
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('id_foyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='maison_app.foyer')),
            ],
            options={
                'db_table': 'piece',
            },
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('id_foyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maison_app.foyer')),
                ('id_piece', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maison_app.piece')),
            ],
            options={
                'db_table': 'inventaire',
            },
        ),
        migrations.CreateModel(
            name='Dispositif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('capteur', 'Capteur'), ('lampe', 'Lampe'), ('thermostat', 'Thermostat')], max_length=50)),
                ('etat', models.BooleanField(default=False)),
                ('id_foyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maison_app.foyer')),
                ('id_piece', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maison_app.piece')),
            ],
            options={
                'db_table': 'dispositif',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('id_foyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maison_app.foyer')),
                ('id_piece', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maison_app.piece')),
            ],
            options={
                'db_table': 'animal',
            },
        ),
        migrations.CreateModel(
            name='PreferenceUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_tache', models.CharField(choices=[('nettoyage', 'Nettoyage'), ('cuisine', 'Cuisine'), ('courses', 'Courses'), ('entretien', 'Entretien')], max_length=50)),
                ('preference', models.CharField(choices=[('aime', 'Aime'), ('desapprouve', 'Désapprouve')], max_length=20)),
                ('disponibilite', models.CharField(choices=[('matin', 'Matin'), ('soir', 'Soir'), ('jour', 'Jour')], max_length=20)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'preference_utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Recompense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('semaine', models.DateField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recompense',
            },
        ),
        migrations.CreateModel(
            name='Statistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_taches_done', models.IntegerField(default=0)),
                ('temps_connexion', models.TimeField(null=True)),
                ('date_stat', models.DateField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'statistique',
            },
        ),
        migrations.CreateModel(
            name='SuggestionTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('priorite', models.CharField(choices=[('Haute', 'Haute'), ('Moyenne', 'Moyenne'), ('Basse', 'Basse')], max_length=20, null=True)),
                ('date_suggestion', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('proposee', 'Proposée'), ('acceptee', 'Acceptée'), ('rejetee', 'Rejetée')], max_length=20)),
                ('id_foyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maison_app.foyer')),
            ],
            options={
                'db_table': 'suggestion_tache',
            },
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date_limite', models.DateField(blank=True, null=True)),
                ('priorite', models.CharField(blank=True, choices=[('Haute', 'Haute'), ('Moyenne', 'Moyenne'), ('Basse', 'Basse')], max_length=20, null=True)),
                ('id_foyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maison_app.foyer')),
                ('id_piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maison_app.piece')),
                ('id_statut', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maison_app.statuttache')),
            ],
            options={
                'db_table': 'tache',
            },
        ),
        migrations.CreateModel(
            name='InteractionIa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commande', models.TextField()),
                ('reponse', models.TextField(blank=True)),
                ('date_interaction', models.DateTimeField(auto_now_add=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_tache', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maison_app.tache')),
            ],
            options={
                'db_table': 'interaction_ia',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_execution', models.DateTimeField(auto_now_add=True)),
                ('duree', models.TimeField(null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maison_app.tache')),
            ],
            options={
                'db_table': 'historique_tache',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_tache', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maison_app.tache')),
            ],
            options={
                'db_table': 'chat_message',
            },
        ),
        migrations.CreateModel(
            name='ActionDispositif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('allumer', 'Allumer'), ('eteindre', 'Éteindre')], max_length=20)),
                ('date_execution', models.DateTimeField(auto_now_add=True)),
                ('id_dispositif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maison_app.dispositif')),
                ('id_tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maison_app.tache')),
            ],
            options={
                'db_table': 'action_dispositif',
            },
        ),
        migrations.CreateModel(
            name='TacheEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maison_app.evenement')),
                ('id_tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maison_app.tache')),
            ],
            options={
                'db_table': 'tache_evenement',
            },
        ),
        migrations.CreateModel(
            name='TacheRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequence', models.CharField(choices=[('Quotidien', 'Quotidien'), ('Hebdo', 'Hebdo'), ('Mensuel', 'Mensuel')], max_length=20)),
                ('dernier_execution', models.DateField(null=True)),
                ('id_tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maison_app.tache')),
            ],
            options={
                'db_table': 'tache_recurrente',
            },
        ),
        migrations.CreateModel(
            name='Tuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
                ('id_tache', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maison_app.tache')),
            ],
            options={
                'db_table': 'tuto',
            },
        ),
        migrations.CreateModel(
            name='UtilisationRessource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_utilisee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_utilisation', models.DateTimeField(auto_now_add=True)),
                ('id_inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maison_app.inventaire')),
                ('id_tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maison_app.tache')),
            ],
            options={
                'db_table': 'utilisation_ressource',
            },
        ),
        migrations.CreateModel(
            name='TacheAssignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assignation', models.DateTimeField(auto_now_add=True)),
                ('id_piece', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maison_app.piece')),
                ('id_tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maison_app.tache')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tache_assignee',
                'unique_together': {('id_tache', 'id_user')},
            },
        ),
    ]
