# Generated by Django 5.2.7 on 2025-11-06 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foyer',
            name='nb_pieces',
        ),
        migrations.AddField(
            model_name='tache',
            name='id_animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maison_app.animal'),
        ),
        migrations.AlterModelTable(
            name='invitation',
            table='invitation',
        ),
    ]
