# Generated by Django 5.2.7 on 2025-11-06 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0002_remove_foyer_nb_pieces_tache_id_animal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='id_foyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animaux', to='maison_app.foyer'),
        ),
    ]
