# Generated by Django 5.2.7 on 2025-11-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0003_alter_animal_id_foyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
