# Generated by Django 5.2.7 on 2025-11-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0004_utilisateur_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='foyer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='foyer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='foyers/'),
        ),
        migrations.AlterModelTable(
            name='foyer',
            table=None,
        ),
    ]
