# Generated by Django 5.2.7 on 2025-11-07 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0005_foyer_description_foyer_photo_alter_foyer_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='complete_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_completees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tache',
            name='terminee',
            field=models.BooleanField(default=False),
        ),
    ]
