# Generated by Django 5.2.7 on 2025-11-18 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0006_tache_complete_par_tache_terminee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['date_envoi']},
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='id_tache',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='id_foyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maison_app.foyer'),
            preserve_default=False,
        ),
    ]
