# Generated by Django 5.2.7 on 2025-11-18 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0008_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='id_foyer',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='foyer_actif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs_actifs', to='maison_app.foyer'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='foyers',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs', to='maison_app.foyer'),
        ),
    ]
