# Generated by Django 5.2.7 on 2025-11-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0009_remove_utilisateur_id_foyer_utilisateur_foyer_actif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='animaux/'),
        ),
        migrations.AddField(
            model_name='piece',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pieces/'),
        ),
    ]
