# Generated by Django 5.2.7 on 2025-11-19 11:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0010_animal_photo_piece_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('couleur', models.CharField(default='#0d6efd', max_length=7)),
                ('icone', models.CharField(default='bi-tag', max_length=50)),
            ],
            options={
                'db_table': 'categorie_depense',
            },
        ),
        migrations.AlterModelOptions(
            name='depense',
            options={'ordering': ['-date_depense']},
        ),
        migrations.RemoveField(
            model_name='budget',
            name='montant_restant',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='montant_total',
        ),
        migrations.AddField(
            model_name='budget',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='date_debut',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='montant_limite',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depense',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='depense',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='id_foyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='maison_app.foyer'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='periode',
            field=models.CharField(choices=[('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('annuel', 'Annuel')], default='mensuel', max_length=20),
        ),
        migrations.AlterField(
            model_name='depense',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='depense',
            name='id_foyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='maison_app.foyer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='depense',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budget',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maison_app.categoriedepense'),
        ),
        migrations.AddField(
            model_name='depense',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maison_app.categoriedepense'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('tache_assignee', 'Tâche Assignée'), ('tache_complete', 'Tâche Complétée'), ('tache_rappel', 'Rappel Tâche'), ('budget_alerte', 'Alerte Budget'), ('nouveau_membre', 'Nouveau Membre'), ('message', 'Message')], max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('id_foyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maison_app.foyer')),
                ('id_tache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maison_app.tache')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-date_creation'],
            },
        ),
    ]
