# Generated by Django 5.2.7 on 2025-11-19 12:48

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0011_categoriedepense_alter_depense_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recompense',
            options={'ordering': ['-date_obtention']},
        ),
        migrations.RemoveField(
            model_name='recompense',
            name='semaine',
        ),
        migrations.AddField(
            model_name='recompense',
            name='date_obtention',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 19, 12, 47, 3, 250650, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recompense',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recompense',
            name='icone',
            field=models.CharField(default='bi-star', max_length=50),
        ),
        migrations.AddField(
            model_name='recompense',
            name='id_tache',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maison_app.tache'),
        ),
        migrations.AddField(
            model_name='recompense',
            name='nom',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recompense',
            name='type',
            field=models.CharField(choices=[('points', 'Points'), ('badge', 'Badge'), ('trophy', 'Trophée')], default='points', max_length=20),
        ),
        migrations.AlterField(
            model_name='recompense',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recompenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recompense',
            name='points',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='Trophee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('100', '100 tâches complétées'), ('50', '50 tâches complétées'), ('10', '10 tâches complétées'), ('streax', 'Streak: 7 jours consécutifs'), ('rapide', 'Complété en moins de 2h'), ('premier', 'Première tâche'), ('social', '5 invitations acceptées')], max_length=50)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icone', models.CharField(max_length=50)),
                ('date_obtention', models.DateTimeField(auto_now_add=True)),
                ('debloque', models.BooleanField(default=False)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trophees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trophee',
                'ordering': ['-date_obtention'],
                'unique_together': {('id_user', 'type')},
            },
        ),
    ]
