# Generated by Django 5.2.7 on 2025-11-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0012_alter_recompense_options_remove_recompense_semaine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
