# Generated by Django 5.2.7 on 2025-12-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0013_utilisateur_photo_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('tresorier', 'Trésorier'), ('membre', 'Membre'), ('junior', 'Junior'), ('invite', 'Invité'), ('observateur', 'Observateur')], default='membre', max_length=20),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('tresorier', 'Trésorier'), ('membre', 'Membre'), ('junior', 'Junior'), ('invite', 'Invité'), ('observateur', 'Observateur')], default='membre', max_length=20),
        ),
    ]
