# Generated by Django 5.2.7 on 2025-12-05 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0014_remove_superviseur_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('tache_assignee', 'Tâche Assignée'), ('tache_complete', 'Tâche Complétée'), ('tache_rappel', 'Rappel Tâche'), ('budget_alerte', 'Alerte Budget'), ('nouveau_membre', 'Nouveau Membre'), ('message', 'Message'), ('demande_modification', 'Demande de Modification')], max_length=20),
        ),
        migrations.CreateModel(
            name='DemandeModificationDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nouvelle_date', models.DateField()),
                ('message', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('id_tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_modification', to='maison_app.tache')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_modification', to=settings.AUTH_USER_MODEL)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'demande_modification_date',
                'ordering': ['-date_creation'],
            },
        ),
    ]
