# Generated by Django 5.2.7 on 2025-12-05 17:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0015_add_demande_modification_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriedepense',
            options={'ordering': ['ordre', 'nom']},
        ),
        migrations.AddField(
            model_name='categoriedepense',
            name='est_categorie_principale',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categoriedepense',
            name='ordre',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categoriedepense',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='maison_app.categoriedepense'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='montant_limite',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
