# Generated by Django 5.2.7 on 2025-12-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0017_populate_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='cree_par',
        ),
        migrations.AddField(
            model_name='invitation',
            name='nom',
            field=models.CharField(blank=True, help_text="Nom optionnel pour identifier l'invitation (ex: 'Invitation famille', 'Invitation1')", max_length=100),
        ),
        migrations.AlterModelTable(
            name='foyer',
            table='foyer',
        ),
    ]
