# Generated by Django 5.2.7 on 2025-12-05 21:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0018_remove_invitation_cree_par_invitation_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='description',
            field=models.TextField(blank=True, help_text='Description de la fonction de la pièce'),
        ),
        migrations.AddField(
            model_name='piece',
            name='type_piece',
            field=models.CharField(choices=[('cuisine', 'Cuisine'), ('chambre', 'Chambre'), ('toilettes', 'Toilettes'), ('salle_de_bain', 'Salle de bain'), ('salle_de_jeux', 'Salle de jeux / Loisirs'), ('salon', 'Salon'), ('buanderie', 'Buanderie / Laverie'), ('garage', 'Garage / Atelier'), ('jardin', 'Jardin / Extérieur'), ('salle_a_manger', 'Salle à manger / Espace commun'), ('bureau', 'Bureau'), ('personnalise', 'Personnalisé')], default='personnalise', help_text='Type de pièce prédéfini ou personnalisé', max_length=50),
        ),
        migrations.AddField(
            model_name='piece',
            name='utilisateurs_autorises',
            field=models.ManyToManyField(blank=True, help_text='Utilisateurs autorisés à accéder à cette pièce. Si vide, tous les membres du foyer peuvent y accéder.', related_name='pieces_autorisees', to=settings.AUTH_USER_MODEL),
        ),
    ]
