# Generated by Django 5.2.7 on 2025-12-05 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0019_piece_description_piece_type_piece_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('categorie', models.CharField(blank=True, help_text='Ex: Fruits, Légumes, Produits laitiers, etc.', max_length=50)),
                ('icone', models.CharField(default='bi-circle', help_text='Icône Bootstrap Icons', max_length=50)),
            ],
            options={
                'db_table': 'ingredient',
                'ordering': ['categorie', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='MenuHebdomadaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaine_debut', models.DateField(help_text='Date de début de la semaine (lundi)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_foyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus_hebdomadaires', to='maison_app.foyer')),
            ],
            options={
                'db_table': 'menu_hebdomadaire',
                'unique_together': {('id_foyer', 'semaine_debut')},
            },
        ),
        migrations.CreateModel(
            name='Repas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=20)),
                ('type_repas', models.CharField(choices=[('petit_dejeuner', 'Petit-déjeuner'), ('dejeuner', 'Déjeuner'), ('diner', 'Dîner'), ('collation', 'Collation')], max_length=20)),
                ('nom', models.CharField(help_text='Nom du plat ou description', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('id_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repas', to='maison_app.menuhebdomadaire')),
            ],
            options={
                'db_table': 'repas',
                'ordering': ['jour', 'type_repas'],
            },
        ),
    ]
