# Generated by Django 5.2.7 on 2025-12-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0020_ingredient_menuhebdomadaire_repas'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliment',
            name='achete',
            field=models.BooleanField(default=False, help_text="Indique si l'aliment a été acheté"),
        ),
    ]
