# Generated by Django 5.2.7 on 2025-12-06 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0021_aliment_achete'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetteGeneree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('titre', models.CharField(max_length=200)),
                ('recette_id_api', models.CharField(help_text="ID de la recette dans l'API (Forkify)", max_length=100)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, help_text='Lien vers la recette originale', null=True)),
                ('temps_preparation', models.IntegerField(blank=True, help_text='Temps de préparation en minutes', null=True)),
                ('portions', models.IntegerField(blank=True, null=True)),
                ('ingredients_recherche', models.TextField(help_text='Ingrédients utilisés pour générer cette recette (séparés par des virgules)')),
                ('ingredients_details', models.JSONField(blank=True, default=list, help_text='Liste complète des ingrédients de la recette')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recettes_generees', to=settings.AUTH_USER_MODEL)),
                ('id_foyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recettes_generees', to='maison_app.foyer')),
            ],
            options={
                'verbose_name': 'Recette générée',
                'verbose_name_plural': 'Recettes générées',
                'db_table': 'recette_generee',
                'ordering': ['-date_creation'],
            },
        ),
    ]
