# Generated by Django 5.2.7 on 2025-12-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0022_recettegeneree'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='date_modification',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='est_modifie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='est_supprime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='type_fichier',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('pdf', 'PDF'), ('autre', 'Autre')], max_length=20),
        ),
    ]
