# Generated by Django 5.2.7 on 2025-12-06 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0023_chatmessage_date_modification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='date_rappel',
            field=models.DateField(blank=True, help_text='Date de rappel (notification automatique)', null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='temps_estime',
            field=models.IntegerField(blank=True, help_text='Temps estimé en minutes', null=True),
        ),
        migrations.CreateModel(
            name='CommentaireTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('id_tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='maison_app.tache')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commentaire_tache',
                'ordering': ['-date_creation'],
            },
        ),
    ]
