# Generated by Django 5.2.7 on 2025-12-06 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0024_tache_date_rappel_tache_temps_estime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Puzzle', max_length=100)),
                ('image_complete', models.ImageField(blank=True, help_text='Image complète du puzzle', null=True, upload_to='puzzles/')),
                ('total_pieces', models.IntegerField(default=50, help_text='Nombre total de pièces du puzzle')),
                ('pieces_initiales', models.IntegerField(default=10, help_text='Nombre de pièces données au début')),
                ('prix_piece', models.IntegerField(default=10, help_text='Coût en points pour acheter une pièce')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('id_piece', models.OneToOneField(limit_choices_to={'type_piece': 'salle_de_jeux'}, on_delete=django.db.models.deletion.CASCADE, related_name='puzzle', to='maison_app.piece')),
            ],
            options={
                'db_table': 'puzzle',
            },
        ),
        migrations.CreateModel(
            name='AchatPiecePuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_piece', models.IntegerField(help_text='Numéro de la pièce achetée')),
                ('points_depenses', models.IntegerField(help_text='Points dépensés pour cet achat')),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats_puzzle', to=settings.AUTH_USER_MODEL)),
                ('id_puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats', to='maison_app.puzzle')),
            ],
            options={
                'db_table': 'achat_piece_puzzle',
                'ordering': ['-date_achat'],
            },
        ),
        migrations.CreateModel(
            name='PiecePuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_piece', models.IntegerField(help_text='Numéro de la pièce (1 à total_pieces)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='puzzles/pieces/')),
                ('placee', models.BooleanField(default=False, help_text='Si la pièce est correctement placée')),
                ('date_obtention', models.DateTimeField(auto_now_add=True)),
                ('date_placement', models.DateTimeField(blank=True, null=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_puzzle', to=settings.AUTH_USER_MODEL)),
                ('id_puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_puzzle', to='maison_app.puzzle')),
            ],
            options={
                'db_table': 'piece_puzzle',
                'unique_together': {('id_puzzle', 'id_user', 'numero_piece')},
            },
        ),
    ]
