# Generated by Django 5.2.7 on 2025-12-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0025_puzzle_achatpiecepuzzle_piecepuzzle'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventaire',
            name='etat',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('a_court', 'À Court')], default='disponible', max_length=10),
        ),
        migrations.AddField(
            model_name='inventaire',
            name='quantite_alerte_min',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventaire',
            name='type_article',
            field=models.CharField(choices=[('aliment', 'Aliment'), ('hygiene', 'Hygiène & Entretien'), ('autre', 'Autre')], default='aliment', max_length=10),
        ),
    ]
