# Generated by Django 5.2.7 on 2025-12-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0026_inventaire_etat_inventaire_quantite_alerte_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='couleur_fond',
            field=models.CharField(default='#FFF9C4', help_text='Couleur de fond en hexadécimal (ex: #FFF9C4)', max_length=7),
        ),
    ]
