# Generated by Django 5.2.7 on 2025-12-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0027_add_couleur_fond_to_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventaire',
            name='unite',
            field=models.CharField(blank=True, help_text='Unité de mesure (kg, L, pièce, etc.)', max_length=20, null=True),
        ),
    ]
