# Generated by Django 5.2.7 on 2025-12-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0028_inventaire_unite'),
    ]

    operations = [
        migrations.AddField(
            model_name='recettegeneree',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instructions de préparation de la recette', null=True),
        ),
    ]
