# Generated by Django 6.0 on 2025-12-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0029_recettegeneree_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='villes_favorites_meteo',
            field=models.JSONField(blank=True, default=list),
        ),
    ]

