# Generated by Django 5.2.7 on 2025-12-10 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0030_utilisateur_villes_favorites_meteo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NiveauSnake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Numéro du niveau (1, 2, 3, ...)', unique=True)),
                ('nom', models.CharField(help_text='Nom du niveau', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description du niveau')),
                ('vitesse', models.IntegerField(default=100, help_text='Vitesse du serpent (ms entre chaque mouvement)')),
                ('score_requis', models.IntegerField(default=0, help_text='Score requis pour passer au niveau suivant')),
                ('points_deblocage', models.IntegerField(default=0, help_text='Points nécessaires pour débloquer (0 = gratuit)')),
                ('actif', models.BooleanField(default=True, help_text='Si le niveau est actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'niveau_snake',
                'ordering': ['numero'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='piecepuzzle',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='piecepuzzle',
            name='id_puzzle',
        ),
        migrations.RemoveField(
            model_name='piecepuzzle',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='id_piece',
        ),
        migrations.CreateModel(
            name='NiveauDebloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_deblocage', models.DateTimeField(auto_now_add=True)),
                ('meilleur_score', models.IntegerField(default=0, help_text='Meilleur score obtenu sur ce niveau')),
                ('date_meilleur_score', models.DateTimeField(blank=True, null=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux_snake_debloques', to=settings.AUTH_USER_MODEL)),
                ('id_niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs_debloques', to='maison_app.niveausnake')),
            ],
            options={
                'db_table': 'niveau_debloque',
                'ordering': ['-date_deblocage'],
                'unique_together': {('id_user', 'id_niveau')},
            },
        ),
        migrations.DeleteModel(
            name='AchatPiecePuzzle',
        ),
        migrations.DeleteModel(
            name='PiecePuzzle',
        ),
        migrations.DeleteModel(
            name='Puzzle',
        ),
    ]
