# Generated by Django 5.2.7 on 2025-12-11 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0031_niveausnake_alter_piecepuzzle_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('tache_assignee', 'Tâche Assignée'), ('tache_complete', 'Tâche Complétée'), ('tache_rappel', 'Rappel Tâche'), ('budget_alerte', 'Alerte Budget'), ('nouveau_membre', 'Nouveau Membre'), ('message', 'Message'), ('demande_modification', 'Demande de Modification'), ('demande_budget', 'Demande de Budget')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trophee',
            name='type',
            field=models.CharField(choices=[('100', '100 tâches complétées'), ('50', '50 tâches complétées'), ('10', '10 tâches complétées'), ('streak', 'Streak: 7 jours consécutifs'), ('rapide', 'Complété en moins de 2h'), ('premier', 'Première tâche'), ('social', '5 invitations acceptées'), ('200', '200 tâches complétées'), ('500', '500 tâches complétées'), ('1000', '1000 tâches complétées'), ('streak_30', 'Streak: 30 jours consécutifs'), ('streak_100', 'Streak: 100 jours consécutifs'), ('efficace', '10 tâches complétées en une journée'), ('organise', "50 tâches complétées à l'avance"), ('collaborateur', "20 tâches assignées à d'autres"), ('punctuel', '50 tâches complétées à temps'), ('maitre', 'Maître de la maison - 100% des tâches complétées'), ('explorateur', 'A visité toutes les pièces'), ('budget', 'Gestionnaire de budget - 10 budgets créés'), ('animal', 'Ami des animaux - 5 animaux ajoutés'), ('note', 'Preneur de notes - 20 notes créées'), ('evenement', 'Organisateur - 10 événements créés')], max_length=50),
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_demande', models.CharField(choices=[('budget', 'Demande de budget'), ('depense', 'Demande de dépense'), ('acces_page', "Demande d'accès à une page"), ('acces_fonctionnalite', "Demande d'accès à une fonctionnalité")], max_length=30)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('reponse', models.TextField(blank=True, help_text="Réponse de l'admin")),
                ('id_foyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='maison_app.foyer')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to=settings.AUTH_USER_MODEL)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_budget_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'demande',
                'ordering': ['-date_creation'],
            },
        ),
    ]
