# Generated by Django 5.2.7 on 2025-12-11 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0032_alter_notification_type_alter_trophee_type_demande'),
    ]

    operations = [
        migrations.AddField(
            model_name='foyer',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foyers_crees', to=settings.AUTH_USER_MODEL),
        ),
    ]
