# Generated by Django 5.2.7 on 2025-12-11 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0033_foyer_cree_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='listecourses',
            name='id_piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listes_courses', to='maison_app.piece'),
        ),
        migrations.AddField(
            model_name='recettegeneree',
            name='id_piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recettes_generees', to='maison_app.piece'),
        ),
        migrations.CreateModel(
            name='MenuSemaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaine_debut', models.DateField(help_text='Date de début de la semaine (lundi)')),
                ('semaine_fin', models.DateField(help_text='Date de fin de la semaine (dimanche)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_foyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus_semaine', to='maison_app.foyer')),
                ('id_piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus_semaine', to='maison_app.piece')),
            ],
            options={
                'db_table': 'menu_semaine',
                'ordering': ['-semaine_debut'],
                'unique_together': {('id_foyer', 'semaine_debut')},
            },
        ),
    ]
