# Generated by Django 5.2.7 on 2025-12-11 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0034_listecourses_id_piece_recettegeneree_id_piece_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepasMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=20)),
                ('type_repas', models.CharField(choices=[('petit_dejeuner', 'Petit-déjeuner'), ('dejeuner', 'Déjeuner'), ('diner', 'Dîner'), ('collation', 'Collation')], max_length=20)),
                ('nom', models.CharField(help_text='Nom du plat ou description', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('id_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repas', to='maison_app.menusemaine')),
            ],
            options={
                'db_table': 'repas_menu',
                'ordering': ['jour', 'type_repas'],
            },
        ),
    ]
