# Generated by Django 5.2.7 on 2025-12-11 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0035_repasmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionFoyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access_budget', models.BooleanField(default=False)),
                ('can_create_depense', models.BooleanField(default=False)),
                ('can_delete_depense', models.BooleanField(default=False)),
                ('can_create_budget', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('id_foyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_utilisateurs', to='maison_app.foyer')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_foyer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'permission_foyer',
                'unique_together': {('id_user', 'id_foyer')},
            },
        ),
    ]
